"""
QuizForge v5.0 — Pdf_generator.py
Generates a formatted, print-ready PDF question paper using fpdf2.
"""

from fpdf import FPDF
import textwrap
import time
import re
import io


class QuizForgePDF(FPDF):
    """Custom FPDF subclass with QuizForge branding."""

    PURPLE_R, PURPLE_G, PURPLE_B = 109, 40, 217      # #6D28D9
    ORANGE_R, ORANGE_G, ORANGE_B = 249, 115, 22      # #F97316
    BEIGE_R,  BEIGE_G,  BEIGE_B  = 245, 236, 215     # #F5ECD7
    DARK_R,   DARK_G,   DARK_B   = 26, 18, 40        # #1A1228
    GRAY_R,   GRAY_G,   GRAY_B   = 100, 90, 120

    def __init__(self, exam: str = "All Exams", total: int = 0):
        super().__init__()
        self.exam  = exam
        self.total = total
        self.set_auto_page_break(auto=True, margin=22)

    def header(self):
        # Purple accent bar
        self.set_fill_color(self.PURPLE_R, self.PURPLE_G, self.PURPLE_B)
        self.rect(0, 0, 210, 4, "F")

        self.set_font("Helvetica", "B", 18)
        self.set_text_color(self.PURPLE_R, self.PURPLE_G, self.PURPLE_B)
        self.set_xy(15, 8)
        self.cell(0, 8, "QuizForge", ln=False)

        self.set_font("Helvetica", "", 8)
        self.set_text_color(self.GRAY_R, self.GRAY_G, self.GRAY_B)
        self.set_xy(15, 17)
        self.cell(0, 5, f"Premium PYQ Engine  ·  {self.exam}  ·  {self.total} Questions", ln=False)

        # Right side
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(self.ORANGE_R, self.ORANGE_G, self.ORANGE_B)
        self.set_xy(140, 8)
        self.cell(55, 8, f"Page {self.page_no()}", align="R")

        # Separator
        self.set_draw_color(self.PURPLE_R, self.PURPLE_G, self.PURPLE_B)
        self.set_line_width(0.4)
        self.line(15, 23, 195, 23)
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(self.GRAY_R, self.GRAY_G, self.GRAY_B)
        ts = time.strftime("%Y-%m-%d %H:%M")
        self.cell(0, 6, f"Generated by QuizForge v5.0  ·  {ts}  ·  quizforge.app", align="C")
        # Orange bottom bar
        self.set_fill_color(self.ORANGE_R, self.ORANGE_G, self.ORANGE_B)
        self.rect(0, 296, 210, 1, "F")

    def section_header(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(self.PURPLE_R, self.PURPLE_G, self.PURPLE_B)
        self.set_text_color(255, 255, 255)
        self.cell(0, 7, f"  {title}", ln=True, fill=True)
        self.ln(2)


def _sanitize(text: str) -> str:
    """Remove characters that can't render in standard FPDF Latin-1."""
    if not text:
        return ""
    # Replace common Unicode
    replacements = {
        '\u2013': '-', '\u2014': '--', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...', '\u00b1': '+/-',
        '\u00d7': 'x', '\u00f7': '/', '\u03b1': 'alpha', '\u03b2': 'beta',
        '\u03b3': 'gamma', '\u03b4': 'delta', '\u03c0': 'pi',
        '\u03bb': 'lambda', '\u03c9': 'omega', '\u2192': '->',
        '\u2190': '<-', '\u2248': '~=', '\u2260': '!=', '\u2264': '<=',
        '\u2265': '>=', '\u00b2': '^2', '\u00b3': '^3',
        '\u00b9': '^1', '\u2080': '0', '\u2081': '1', '\u2082': '2',
        '\u00e9': 'e', '\u00e8': 'e', '\u00e0': 'a', '\u00fc': 'u',
        '\u00c9': 'E', '\u00c8': 'E',
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(questions: list, exam: str = "All Exams") -> bytes:
    """
    Generate a full question paper PDF with answer key.
    Returns raw PDF bytes.
    """
    pdf = QuizForgePDF(exam=exam, total=len(questions))
    pdf.add_page()

    # ── Cover block ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(pdf.PURPLE_R, pdf.PURPLE_G, pdf.PURPLE_B)
    pdf.cell(0, 12, "QUESTION PAPER", ln=True, align="C")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
    pdf.cell(0, 7, f"Exam: {_sanitize(exam)}   |   Total Questions: {len(questions)}", ln=True, align="C")

    # Stats row (count by exam)
    exam_counts: dict = {}
    for q in questions:
        e = q.get("exam", "GK")
        exam_counts[e] = exam_counts.get(e, 0) + 1
    stats_str = "  |  ".join(f"{k}: {v}" for k, v in sorted(exam_counts.items()))
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(pdf.GRAY_R, pdf.GRAY_G, pdf.GRAY_B)
    pdf.cell(0, 6, _sanitize(stats_str), ln=True, align="C")

    # Instructions box
    pdf.ln(4)
    pdf.set_fill_color(pdf.BEIGE_R, pdf.BEIGE_G, pdf.BEIGE_B)
    pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
    pdf.set_font("Helvetica", "B", 8)
    x0 = pdf.get_x()
    pdf.rect(15, pdf.get_y(), 180, 22, "F")
    pdf.set_xy(18, pdf.get_y() + 3)
    pdf.cell(0, 5, "INSTRUCTIONS:", ln=True)
    pdf.set_xy(18, pdf.get_y())
    pdf.set_font("Helvetica", "", 7.5)
    pdf.cell(0, 4, "1) Each MCQ has exactly one correct answer.  2) Negative marking as specified per question.", ln=True)
    pdf.set_xy(18, pdf.get_y())
    pdf.cell(0, 4, "3) Numerical answers must be written to 2 decimal places.  4) Answer key is provided at the end.", ln=True)
    pdf.ln(10)

    # ── Questions ──────────────────────────────────────────────────────────
    current_exam = None
    for idx, q in enumerate(questions, 1):
        exam_tag = q.get("exam", "GK")
        if exam_tag != current_exam:
            current_exam = exam_tag
            subject_map = {
                "JEE":  "JOINT ENTRANCE EXAMINATION (JEE)",
                "NEET": "NATIONAL ELIGIBILITY CUM ENTRANCE TEST (NEET)",
                "UPSC": "UNION PUBLIC SERVICE COMMISSION (UPSC)",
                "CAT":  "COMMON ADMISSION TEST (CAT)",
                "SAT":  "SCHOLASTIC ASSESSMENT TEST (SAT)",
                "GK":   "GENERAL KNOWLEDGE (GK)",
            }
            label = subject_map.get(exam_tag, exam_tag)
            pdf.section_header(f"SECTION: {label}")

        # Check page space
        if pdf.get_y() > 255:
            pdf.add_page()

        # Q number + meta
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(pdf.ORANGE_R, pdf.ORANGE_G, pdf.ORANGE_B)
        chapter = _sanitize(q.get("chapter", ""))
        year    = _sanitize(str(q.get("year", "")))
        diff    = _sanitize(q.get("difficulty", ""))
        marks   = q.get("marks", 1)
        neg     = q.get("negative_marks", 0)
        meta_str = f"  [{chapter}  |  {year}  |  {diff}  |  +{marks}/-{neg}]"
        pdf.cell(0, 5, f"Q{idx}.{meta_str}", ln=True)

        # Question text
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
        q_text = _sanitize(q.get("question", ""))
        lines = textwrap.wrap(q_text, width=88)
        for line in lines:
            pdf.cell(0, 5, line, ln=True)
        pdf.ln(1)

        is_num = q.get("type") == "numerical"

        if is_num:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(pdf.GRAY_R, pdf.GRAY_G, pdf.GRAY_B)
            unit = _sanitize(q.get("unit", ""))
            pdf.cell(0, 5, f"   [Numerical Answer — enter value in {unit if unit else 'appropriate units'}]", ln=True)
            pdf.cell(0, 5, "   Answer: ___________________", ln=True)
        else:
            options = q.get("options", {})
            pdf.set_font("Helvetica", "", 9)
            for ltr in ["A", "B", "C", "D"]:
                opt = _sanitize(options.get(ltr, ""))
                if opt:
                    opt_lines = textwrap.wrap(opt, width=80)
                    pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
                    pdf.cell(8, 5, f"  ({ltr})", ln=False)
                    pdf.cell(0, 5, opt_lines[0] if opt_lines else "", ln=True)
                    for extra_line in opt_lines[1:]:
                        pdf.cell(8, 5, "", ln=False)
                        pdf.cell(0, 5, extra_line, ln=True)

        pdf.ln(3)

    # ── Answer Key ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_header("ANSWER KEY")
    pdf.ln(3)

    cols = 5
    col_w = 35
    row_h = 7

    headers = ["Q.No", "Answer", "Chapter", "Year", "Marks"]
    pdf.set_fill_color(pdf.PURPLE_R, pdf.PURPLE_G, pdf.PURPLE_B)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for h, w in zip(headers, [12, 20, 80, 20, 15]):
        pdf.cell(w, 7, h, border=1, fill=True)
    pdf.ln()

    for idx, q in enumerate(questions, 1):
        if pdf.get_y() > 268:
            pdf.add_page()

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)

        # Alternate row shading
        if idx % 2 == 0:
            pdf.set_fill_color(pdf.BEIGE_R, pdf.BEIGE_G, pdf.BEIGE_B)
            fill = True
        else:
            fill = False

        is_num = q.get("type") == "numerical"
        ans = str(q.get("numericalAnswer", "")) if is_num else q.get("answer", "A")
        chapter = _sanitize(q.get("chapter", ""))[:30]
        year = _sanitize(str(q.get("year", "")))[:6]
        marks = f'+{q.get("marks",1)}/-{q.get("negative_marks",0)}'

        # Highlight correct answer
        pdf.cell(12, 6, str(idx), border=1, fill=fill)
        pdf.set_text_color(pdf.ORANGE_R, pdf.ORANGE_G, pdf.ORANGE_B)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(20, 6, _sanitize(ans), border=1, fill=fill)
        pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(80, 6, chapter, border=1, fill=fill)
        pdf.cell(20, 6, year, border=1, fill=fill)
        pdf.cell(15, 6, marks, border=1, fill=fill)
        pdf.ln()

    # ── Explanations ────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_header("EXPLANATIONS")
    pdf.ln(3)

    for idx, q in enumerate(questions, 1):
        exp = q.get("explanation", "")
        if not exp:
            continue
        if pdf.get_y() > 258:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(pdf.PURPLE_R, pdf.PURPLE_G, pdf.PURPLE_B)
        pdf.cell(0, 5, f"Q{idx}. {_sanitize(q.get('chapter',''))} ({q.get('year','')})", ln=True)

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(pdf.DARK_R, pdf.DARK_G, pdf.DARK_B)
        exp_clean = _sanitize(exp)
        for line in textwrap.wrap(exp_clean, width=95):
            pdf.cell(0, 4.5, line, ln=True)
        pdf.ln(2)

    return bytes(pdf.output())